<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: kornel
 * Date: Thu, 17 Sep 2009 00:25:25 +0100
 */

$conf['title'] = 'PHPTAL Wiki';
$conf['template'] = 'PHPTAL';
$conf['license'] = 'gnufdl';
$conf['youarehere'] = 1;
$conf['typography'] = '0';
$conf['showuseras'] = 'username';
$conf['useheading'] = 'content';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['notify'] = 'pornel@pornel.net';
$conf['subscribers'] = 1;
$conf['jpg_quality'] = 80;
$conf['useslash'] = 1;
$conf['autoplural'] = 1;
$conf['send404'] = 1;
$conf['rss_type'] = 'atom1';

// end auto-generated content
