<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: kornel
 * Date: Wed, 16 Sep 2009 12:27:43 +0200
 */

$conf['title'] = 'PHPTAL';
$conf['template'] = 'A_Free_Worldic';
$conf['license'] = 'gnufdl';
$conf['typography'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['notify'] = 'pornel@pornel.net';
$conf['subscribers'] = 1;
$conf['jpg_quality'] = 80;
$conf['useslash'] = 1;
$conf['autoplural'] = 1;
$conf['send404'] = 1;
$conf['rss_type'] = 'atom1';

// end auto-generated content
